### ISSUE TITLE
Weekly or Bi-Weekly meetings

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/meta#14]
As the community grows we should have public meetings, particularly to have a space for people to show off their projects and for those to check up on the status of various organizational projects.

How frequent do you think we should have them?

**Comment by torch2424** [comment]
Totally on board with this! 😄 

> How frequent do you think we should have them?

I'd vote bi-weekly, as we found weekly to be too frequent in the rust/wasm meetings 😄

And concerning Timing, I'd say maybe for Wednesday, 17:00 UTC.

For reference, [rust/wasm](https://github.com/rustwasm/team/issues/288) meets on Thursdays, 17:00 UTC. [WebAssembly CG](https://github.com/WebAssembly/meetings/blob/master/2019/CG-10-01.md) meets Tuesdays 16:00 UTC, and [WASI CG](https://github.com/WebAssembly/WASI/blob/master/meetings/2019/WASI-09-12.md) Thursdays, 16:00 UTC . 

Meaning Wednesdays 17:00 UTC shouldn't have too much conflict with other Wasm community meetings to my knowledge, so we would be good to go 😄

**Comment by willemneal** [comment]
Sounds like good time to me.  We should also perhaps have a way for people to join so that we can have teams they can request to join.

**Comment by torch2424** [comment]
> Sounds like good time to me.

Awesome, if I may ask, how to do these times work for @MaxGraey and @dcodeIO . No one has to join if they don't want to, but would like your input on the timing, especially considering your timezones 😄 

> We should also perhaps have a way for people to join so that we can have teams they can request to join.

Join which? Teams or the meetings? I've seen a lot of the community use [Zoom, which is free for personal meetings](https://zoom.us/pricing). In terms of the meetings, I've seen people just create github issues for each meeting. And then post the zoom link there for people to join 😄

**Comment by willemneal** [comment]
I mean for the teams aspect.  As there is currently not an easy way for people to join.  Also do you know of anyway to connect a chat like gitter with slack?  Or should we revive/advertise the discord?

**Comment by torch2424** [comment]
@willemneal 

> I mean for the teams aspect. As there is currently not an easy way for people to join. 

Ah, do we want it to be super easy for people to join a team? I thought we would want it to be like someone asks or gets invited? 🤔 😄 

> Also do you know of anyway to connect a chat like gitter with slack? Or should we revive/advertise the discord?

Yeah I think I brought this up in the slack earlier, kind of debating if we wanted to be a public forum, or more of a team type thing. I think we were hoping that people would open issues and things, and then invite them to the slack if they've been active for a bit. But maybe it is worth maybe making a public slack channel, or re-advertise the discord for more one-off conversations? 😄

**Comment by chicoxyzzy** [comment]
I'm barely involved, but I don't see any reasons why meetings shouldn't be public. wasm CG and Rust-wasm meetings are open to everyone (well, for wasm cg one should have w3c account) and that helps to be in touch with community.

**Comment by torch2424** [comment]
@chicoxyzzy Oh yeah! I think the plan here to have the meetings public for sure 😄

**Comment by torch2424** [comment]
Got confirmation from @dcodeIO that the time and day works for them, and @MaxGraey that the day would work 😄 

So I'm thinking we can do the first one Wednesday, November, 17:00 UTC. Then, we can announce it on Twitter per, @MaxGraey suggestion?

Let me know if this sounds good, and if so, we got our first meeting! 😄

**Comment by torch2424** [comment]
@MaxGraey Yep, that is the one I am suggesting, my apologies! Updated my comment 😂

**Comment by torch2424** [comment]
So per a discussion on the slack, it seemed like 17:00 UTC did not seem like a good time for @MaxGraey and myself after all. 

We also didn't really promote the meetings or anything on the AssemblyScript Twitter. Thus, I am proposing we cancel tommorrows meeting, and doing November 20th, 18:00 UTC instead. 

This fits a bit better with some of the time frame of the team. Also, gives us time to inform more people about the event, and maybe setup some tooling for things like Zoom 😄 

cc @willemneal

**Comment by torch2424** [comment]
Closing this in favor of #15 as we are starting to do our meetings! 😄 🎉
