### ISSUE TITLE
Project Goals and Roadmap

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/meta#2]
Inspired by: https://opensource.guide/best-practices/ . As well as advice from other Open Source "Core Team" members on other projects.

I think it would be good to express where we see / want the project to go. That way we know what/where to ask for help, and for people who want to support the project where their efforts are best placed on a common goal :smile: 

**Personally, I feel this way (and have had some of these assumptions confirmed before by others):**

* I think they are going to be [a lot of JavaScript](https://insights.stackoverflow.com/survey/2019#technology) developers who write and care about the web that will want to start using WebAssembly. And have the capacity to successfully write large applications in complex enviornments. (I remember seeing a funny tweet about this, but can't find it. TL;DR Web developers brought Javascript to the server. Why wouldn't they be able to handle Wasm)

* AssemblyScript can (and honestly, currently) be a great way to learn the technology, and **how it fits into your current JS/TS workflow and tech stack**

* AssemblyScript has definitely already proven itself in [benchmarks against other languages](https://developers.google.com/web/updates/2019/02/hotpath-with-wasm), and [been publicly "blessed" by a major company](https://youtu.be/njt-Qzw0mVY)

* Currently, seems like big(er) companies are investing on Wasm on the Server, vs. the browser. Probably because there is more money in it (Edge networking / serverless). If most of this is currently/mostly done in node by node developers. AssemblyScript would probably be poised to get those developers to start writing/porting to wasm.

* AssemblyScript I think is appealing as a "user language" for a lot of "platforms" that run Wasm under the hood (game engines, scripting, etc...).

* AssemblyScript is great for those who really just want to follow the [MDN spec of Wasm](https://developer.mozilla.org/en-US/docs/WebAssembly), and start using it. Especially in the low(er) level case, or building Wasm from scratch.

**Caveats / Biases:**

* I am a Javascript developer.

* I write a lot of AssemblyScript, and have been friends with ya'll for a while :joy: 

**Suggestions (please feel free to disagree, thought of this on the spot :joy: ) for goals**

* Continue with keeping feature parity for more major functionality, and developer experience features (Wasi, Grabage Collection, etc...)

* Try to make the "onboarding" really simple, for both new, and existing JavaScript projects.

* Try to write some tools for things like serverless and blockchain? :thinking: 

Let me know what ya'll think. Thank you for the length-y read. My apologies! :joy: @MaxGraey @dcodeIO @jtenner

**Comment by torch2424** [comment]
Moving over some of the previous discussion from slack

@MaxGraey 

> I think will be great have better description about AssemblyScript goals on main page. AS is great platform for implement and battle test experimental proposals because it much easier to integrate compare to others more complex and mature platforms/languages. So I guess that’s how we could contribute to the common cause

@dcodeIO 

> Regarding the goals, I think that different people have different goals. Some people, like when it comes to blockchain, want an alternative to TS, others want a way to write low-level WASM in a nicer syntax and so on. So yeah, maybe we should collect our goals and write them down in a sentence or two? Personally I'm interested in the overall success of the project, so I'm hopping from intermediate goal to intermediate goal to make the goals, not only mine, happen :slightly_smiling_face:

**Comment by dcodeIO** [comment]
Agreeing with all of the suggestions, just wanting to note another WASM GC dilemma that we might be heading towards: From my perspective, the sooner we can scrap our custom runtime the better the overall experience / the smaller and more convenient generated modules will become. However, since browser engines will most likely spearhead this, and 3rd party WASM runtimes possibly (I'm guessing) being behind a fair bit because these don't have use an existing GC ecosystem, these goals might contradict because our sponsors especially rely on being able to run modules in non-browser VMs. My hope there is that someone (maybe even us) will make a "module using WASM GC" to "module downleveling WASM GC to an included runtime" tool :)

**Comment by torch2424** [comment]
@dcodeIO 

> Agreeing with all of the suggestions

Rad! I'll go ahead an open up a PR to add goals to the Readme :smile: 

>  just wanting to note another WASM GC dilemma that we might be heading towards: From my perspective, the sooner we can scrap our custom runtime the better the overall experience / the smaller and more convenient generated modules will become. However, since browser engines will most likely spearhead this, and 3rd party WASM runtimes possibly (I'm guessing) being behind a fair bit because these don't have an existing GC ecosystem, these goals might contradict because our sponsors especially rely on being able to run modules in non-browser VMs. My hope there is that someone (maybe even us, Binaryen would be even better, but that's a hard nut again) will make a "module using WASM GC" to "module downleveling WASM GC to an included runtime" kind-of-thing.

Ah yes I definitely agree here. Just from talking to others and things, I 'd meet a lot of people that would say "AssemblyScript is amazing, but would be great if it had GC". So I'm super duper stoked we have a solution for that (And of course thank you so much for your hard work). And I 100% agree, we don't want to have to re-invent the wheel for upcoming standards, or something we know will eventually get thrown away.

I think it'd be good to also highlight here than another goal:

* Preserve a lightweight runtime, and utilize platform APIs as they are added to accomplish high-level features.

Does that make sense? Feel free to re-work my wording. 

What I'm trying to say here in a sentence is: "Yo, we don't want a small runtime because it's fast, and small modules. And we will minimize the runtime, and it would be your responsibility to keep up with features or work with older versions of the project."

Which honestly, I don't think it is really too much of a "controversial" stance to take. Because you will often see [serverless platforms add new versions of a backing language/runtime overtime](https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/). Meaning, I feel like runtimes would then be responsible to "add support" for AssemblyScript versions. What do you think? :smile:

**Comment by dcodeIO** [comment]
I think the core of my concerns is that we still have to ensure that when following the goals it must still somehow work for existing actual users (currently: blockchain). Maybe this can be summarized in

* Target feature parity with WebAssembly and related technology
* Stay as close to TypeScript syntax and JavaScript APIs as reasonable
* Support non-browser use cases well (i.e. blockchain)
* Make it easy to get started using AssemblyScript (installation, docs, examples)

so it also covers future "features vs non-browser support" alignment. Does that make sense? :)

**Comment by MaxGraey** [comment]
Also need to think what tools we lack currently. For testing we have `as-pect` thankfully @jtenner. We definitely should improve module resolution experience which  partially could resolved in [that PR](https://github.com/AssemblyScript/assemblyscript/pull/594). Will be great have own language server and linter but this no high priority I guess. Once thing which also may be useful especially for non-web / serverless applications is tools something similar to Valgrind fot for Wasm. I found only [Wasabi](https://github.com/danleh/wasabi). Maybe someone else sees what I missed?

**Comment by MaxGraey** [comment]
Also will be great if any minor release have changelog and announce in twitter with link to this changelog or inline description of top changes =)

**Comment by MaxGraey** [comment]
I guess it could be just some github bot which collect all merged commits and create list from them. @torch2424 did you know something similar to this?

**Comment by torch2424** [comment]
> Also need to think what tools we lack currently. For testing we have as-pect thanks to @jtenner. We definitely should improve module resolution experience which partially could resolved in that PR. Will be great have own language server and linter but this no high priority I guess. Once thing which also may be useful especially for non-web / serverless applications is tools something similar to Valgrind but for Wasm. I found only Wasabi. Maybe someone else sees what I missed?

Been thinking about this as well :smile: Been having a hard time thinking of something. I'll probably do some fun serverless stuff sometime soon just to see the experience. Poking around, `create-X-app` has always been a fun thing. That being said, we already have `asinit` :thinking: Maybe it's worth opening an issue to dump ideas? :smile: 

> Also will be great if any minor release have changelog and announce in twitter with link to this changelog or inline description of top changes =)

Agreed :smile: 

> I guess it could be just some github bot which collect all merged commits and create list from them. @torch2424 did you know something similar to this?

I currently don't, but I can look into it if you would like? :smile:

**Comment by torch2424** [comment]
Will set this to close in #4 once it is merged :smile:

**Comment by bowenwang1996** [comment]
@torch2424 We use assemblyscript for smart contract development at [Near](https://nearprotocol.com/) and you can check out some examples [here](https://studio.nearprotocol.com/).
