### ISSUE TITLE
Define Roles / Team / Membership

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/meta#3]
Inspired by: https://opensource.guide/leadership-and-governance/#what-are-examples-of-formal-roles-used-in-open-source-projects and suggestions from other larger open source project core team members.

I think having roles (at least soft roles) would really help in terms of organization of the project, and knowing who to ask about topics (both internally and externally).

Where the roles don't need to be as concrete as "Compiler Engineer", something as vague as a "Core Team", or "Maintainers" on the project (or other related projects that help encourage the overall project goals).

With this in mind, I think this can help when other projects want to know: "Hey, I want to align with the AssemblyScript project, on our project. Who would be a good person(s) to reach out to?".

Along with this, we definitely don't want to build an "exculsive club". I think it should kind of be like our current slack. Where anyone can really join, just ask for an invite :smile: But depending on what they have contributed (not just code) can ask or be approached to be put into different "general" roles. I know this may read kinda weird, so I can give some examples to help define my idea here :smile: 

@MaxGraey @dcodeIO @jtenner would love your opinion!

**Comment by torch2424** [comment]
Moving some of the previous discussion from Slack

@dcodeIO 

> I'm always glad when responsibility is taken off my shoulders so I can focus on technical aspects :slightly_smiling_face:. Would love to remain involved in all of this ofc, but the less I have to talk, the more I can write code :slightly_smiling_face:

@MaxGraey 

> Of course, there is no division into duties and roles) There are just things that you like and do well, so why not marked this? Someone like only technical work, someone good in management and/or communication) But still do a lot of works in technical direction

@dcodeIO 

> ofc I also don't mind to be contacted if there's something cool on the horizon, will relay that to you guys anyway so we can think about it. Maybe we could make an email address for the project that people can use to reach out, forwarding to all of us?

@MaxGraey 

> Since the team is still small, it would be possible to do the following: everyone would try on himself some supplemental role which would not burden him too much, but at the same time helped the development of the project. @dcode has already taken on quite a lot - for example, supporting documentation) I am eager to attract new sponsors (with varying success of course). As well as  helper for first adopters. I could still do something, but I’m afraid then I won’t have time for coding at all)

@jtenner

> I'm happy to help with tooling.

@dcodeIO 

> while cleaning up current org teams I figured that we might have 3 teams there: Advocate (everyone contributing by means other than code), Contributors (code) and one internal for Maintainers that I can use to simplify access to the org. ofc one can be in multiple. then also allows every contributor to have an AS badge on their profile :slightly_smiling_face: . maybe we don't even need [Github?] teams at all and can just use repo access. so everyone contributing is a member without putting a label on it, and everything else is just repo write access for specific people

**Comment by dcodeIO** [comment]
> maybe we don't even need [Github?] teams at

Yep, GitHub teams is what I meant, not teams in general. Looks like giving members individual access to the repositories they need makes for more fine-grained control.

For contact, I think that a) a project email address to get in touch quickly relaying to all relevant people so someone can pick up a request easily with everyone being informed plus b) a list of contact persons with a short sentence on their responsibilities on the meta README could work. Does that sound right? :)

**Comment by torch2424** [comment]
@dcodeIO 

> Yep, GitHub teams is what I meant, not teams in general. Looks like giving members individual access to the repositories they need makes for more fine-grained control.

Oh yeah I know what you mean :smile: Yeah I think that makes perfect sense. If someones wants to make changes `AssemblyScript/assemblyscript-donuts`, the definitely probably don't want/need access to other repos haha! :joy: 

> For contact, I think that a) a project email address to get in touch quickly relaying to all relevant people so someone can pick up a request easily with everyone being informed plus b) a list of contact persons with a short sentence on their responsibilities on the meta README could work. Does that sound right? :)

A. Yes, I definitely agree. I know you mentioned this before, and I am totally behind this. Just let me know the email, you want on the readme, and we can figure out how to set up the forwarding between us.

B. Yep, I think that would be great! I'll also add this to my README Pr and we can review it :+1:

**Comment by torch2424** [comment]
Just so no one feels left out (because we've had a lot of awesome people help out this project).

I just opened pr #4 . For anyone following this discussion, or whoever sees my slack. Feel free to ask here if you would like to be a part of the "core team" idea. No worries if not or if so. Don't want this to become some kind of "exclusive club", and want to welcome anyone who is generally interested in the project for the longer term (let me know if this sounds okay @dcodeIO ) :smile: 

For example, looking through the contributors on the main project, and the docs "Built with AssemblyScript":

* @nidin
* @jedisct1

And it is not just code. If you wrote an awesome book, or built anything cool let us know :smile: :+1:

**Comment by jedisct1** [comment]
I can probably not be considered in the core team. But besides maintaining WASA and wasm-crypto, my informal role is to ensure that AssemblyScript can be used in non-browser contexts, too.

I work on Lucet and on the WASI standard, and I try to make these support AssemblyScript as a first-class citizen.

So I'd happy to help with anything related to running server-side AssemblyScript.

**Comment by nidin** [comment]
I would love to join the core team but there is no time left after my daily work and family time. I would consider myself as an `AssemblyScript Evangelist`

**Comment by jtenner** [comment]
I'm here to do little things when I can. Leave me in the Evangelist title if that's okay.

**Comment by willemneal** [comment]
I'll take the developer experience role as most of my focus has been in that area.

**Comment by torch2424** [comment]
@jedisct1

Oh that is sooooooo cool! :smile: Glad to hear that. :+1: Yes, no pressure on joining anything, and you're help is already greatly appreciated.

@nidin 

No worries! Sounds good :smile: 

@jtenner 

Sounds good!

@willemneal 

Sounds good! :smile: 

**So for everyone interested in joining some type of "core team",** don't want to think I'm trying to throw a ton of responsibility on ya'll. Of course this is all open source so, "amount of things done" is all in the air since it's mostly volunteer stuff :smile: Perhaps we can have a "core team", and like "other cool people" or something like that? :joy:

**Comment by jtenner** [comment]
I want the responsibility. Bring it on.

**Comment by jedisct1** [comment]
How about having a "team" and a "core developers" subset?

**Comment by torch2424** [comment]
@jtenner 

Awesome! 😂 

@jedisct1 

That sounds great! I like that naming a bit more. What do you think @dcodeIO ? 😄

**Comment by nidin** [comment]
Sounds good to me.

**Comment by dcodeIO** [comment]
The "Maintainers" role seems a bit odd to me because someone who contributes significant parts occasionally doesn't necessarily have push permissions / be a contact person at any time, which is usually what "Maintainer" implies (is it?). Would probably skip it, or rename to something like "Core Contributors"?

**Comment by torch2424** [comment]
@dcodeIO Ahhh makes sense. Yeah Maintainers is a bit conflicting. 

How about this naming:

"Core Team" -> "Core Team"

"Maintainers" -> "Notable Contributors"

"Contributors" -> "Contributors"

Let me know what you think! 😄

**Comment by dcodeIO** [comment]
Doesn't Microsoft have this "Distinguished Engineer" thing? What about "Distinguished Contributor" 😄

**Comment by torch2424** [comment]
@dcodeIO So I looked up some definitions of "Distinguished" and asked my partner at home, and yeah I think it makes sense! 

I also, plan to have a little description of each "role" so if it seems unclear, hopefully :smile:  that will help

Will add this to #4 :+1: 

If no one has objections to this, I think I'll go ahead and mark this for closing in the PR once it is merged :tada:

**Comment by bowenwang1996** [comment]
Does everyone on "core-team" have write access to Assemblyscript repo? I feel like we should maybe be more careful with that

**Comment by torch2424** [comment]
@bowenwang1996 Ah, so the core team is more defined as those who help the project. Commit access to repos is more of a technical decision to be made by @dcodeIO as decided in the governance (which is still a WIP until #4 is merged). But the Core team can be anyone who builds seperate tools, does evangelism, or helps the project grow in general :smile:

**Comment by bowenwang1996** [comment]
Yes that's what I thought. I think github now has [triage](https://github.blog/changelog/2019-05-23-triage-and-maintain-roles-beta/) role, which might be something worth considering.

**Comment by torch2424** [comment]
Ah yeah, you make a good point. Definitely should keep that in mind :) I'll open an issue around that once we merge #4 :)

**Comment by torch2424** [comment]
So spoke a bit with @dcodeIO about #4 and we felt still a little uneasy about the "layers" of the team. And started looking at other open source projects and what they do. For Example:

* Vue - https://vuejs.org/v2/guide/team.html#active-core-team-members

* Rust/Wasm - https://github.com/rustwasm/team/blob/master/GOVERNANCE.md#governance-of-the-rustwasm-organization

* AMP - https://github.com/ampproject/meta/tree/master/working-groups

Vue kind of shows us the path we [could be] going down. A very large core team, where it's not too clear what each person does unless you read every member, and a very large list of people who no longer contribute.

But I'd like to propose maybe we organize into "multiple" teams beyond just "core" and "distinguished". I will admit, this is going back on my original post, but now I see the error in my idea :joy: 

Following what Rust/Wasm and AMP are doing. Maybe we can divide the teams into the following:

* "Compiler" - Team that works on the main AssemblyScript/assemblyScript repo.
* "Evangelism & Outreach" - Team that works on talks, giving feedback on messaging, and writes articles to help grow popularity.
* "Developer Experience" - Team that works on tools and anything that helps people be productive with the language.

Each Team will have a description to be less vauge. And similar to the rust/wasm organization, membership should be encourage, upon significant contributions. Where significant should probably just be a "medium bar". Rust/wasm describes this as two to three "large" contributions. And membership should probably be done by consensus :smile: 

Also, people should be able to hold membership in multiple teams (E.g @jtenner would probably fall into both Developer Experience, and Evangelism).

Also, in our discussion we still find their to be a lot of value in having teams:

1. Place of contact, and group of people working on a similar goal to focus our efforts (on the member's own accord of course)
2. Motivating for contributors, and it feels good to be a part of something :smile: 

Lastly, I think we should reserve teams to be "active" members. To avoid the documents becoming too long. But it should be encouraged that members who have become "inactive" (Either in not having the time to contribute, or just don't want any "responsibility" at the time) would be welcomed back with open arms at any time (by essentially doing some contributions / chatting again with probably a "low-medium" bar). From this, I'd probably consider @nidin as "inactive", but of course, if they had the time would always be welcomed as a member of a team :smile: Let me know if this is alright with you (mean this with good intent feel free to call me out :joy: ) 

Let me know what ya'll think!

@dcodeIO  @MaxGraey @jtenner @willemneal @nidin @bowenwang1996

**Comment by bowenwang1996** [comment]
I think the rust model https://www.rust-lang.org/governance#Moderation-team could be a good one

**Comment by torch2424** [comment]
@bowenwang1996 Hmmm, I'd be open to having an overarching team. The reason why I didn't mention one here, is simply because defining what would make you a member is kind of hard and "exclusive"? :thinking: But if we decide to go with it, I'll let @dcodeIO decide the members.

Also, @bowenwang1996 I'd think you'd maybe fall into "Developer Experience"? As the near library is about making blockchain easier on AssemblyScript correct? :smile:

**Comment by bowenwang1996** [comment]
Maybe at such an early stage it is not beneficial to spread out and have multiple teams? I am not sure and maybe we should consult other large open-source projects. As for me, yes, I am focusing on developer experience, although that also lead me to look into compiler internals and started working on the resolver (See my PR [here](https://github.com/AssemblyScript/assemblyscript/pull/686) and [here](https://github.com/AssemblyScript/assemblyscript/pull/689)).

**Comment by torch2424** [comment]
@bowenwang1996 

> Maybe at such an early stage it is not beneficial to spread out and have multiple teams? 

So I do agree it is kind of weird to have a few micro teams. But I think it is valuable to try and get it "right" now, rather than try and change it later and discourage others.

>  I am not sure and maybe we should consult other large open-source projects.

I can definitely do that. Currently, I am working on the AMP Project, so I can consult some colleagues on Monday. I also can try reaching out to some other projects as well if you would like?

> As for me, yes, I am focusing on developer experience, although that also lead me to look into compiler internals and started working on the resolver (See my PR here and here).

Rad, well I can put you in both compiler and developer experience :smile:

**Comment by torch2424** [comment]
@bowenwang1996 Just want to bump this is you get the chance :smile: I think this issue is probably the last stopping #4 . But toally open to discussing till we find an answer that makes sense :smile: :+1:

**Comment by bowenwang1996** [comment]
I don't have a strong opinion on this so you can decide.

**Comment by torch2424** [comment]
@bowenwang1996 Awesome, thanks for the response.

If you don't have a strong opinion, then I'll go with the "multiple teams" idea for the reasons I said above 😄 

Will update #4 when I get the chance 👍
