### ISSUE TITLE
Define a Governance

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/meta#7]
I think it'd also be good to do this sooner than later. And as this suggests: https://opensource.guide/leadership-and-governance/#what-are-some-of-the-common-governance-structures-for-open-source-projects

And since we are a "smaller" project, I suggest we go with **BDFL** where we go with the original author @dcodeIO :smile: 

Let me know if anyone thinks otherwise :+1:

**Comment by dcodeIO** [comment]
Considering myself more of a project lead *in technical aspects*, and I'm really glad that you've picked up to structure the organizational side and that Max is helping not only with stdlib but also with everything sponsoring related. Guess it's best described as a technical BDFL and an organizational meritocracy, if that makes sense :)

**Comment by torch2424** [comment]
Rad! That makes perfect sense to me :smile: I'll go ahead and add this to #4 and mark this issue for closing :smile:

**Comment by torch2424** [comment]
Actually, for the organizational side, I would actually prefer "Liberal contribution", as it seems similar to meritocracy, but seems to be a bit more flexible, and more based on "current active" community members, rather than ones who may just lurk after a while.

I reflected this in #4 , but super open to discussing and changing this if needed :smile:

**Comment by dcodeIO** [comment]
My thought here was that everyone on the "core team" (the meritocracy) would have a voice on organizational things. Here, my expectation is that these are the people most active around the compiler, and not lurking, so have the necessary background to make the right decisions in this regard where "liberal" (everyone with varying backgrounds) might lead us into more situations where a BDFL might have to intervene. I also don't like the term "meritocracy", but the description of the governance model seemed to fit.

**Comment by torch2424** [comment]
Rad, I'll put it back, and if anyone asks, we can point them here :smile:
