### ISSUE TITLE
On "Stay as close to TypeScript syntax and JavaScript APIs as reasonable"

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/meta#9]
https://github.com/AssemblyScript/meta/pull/4 initially included the following as on of our goals

* Stay as close to TypeScript syntax and JavaScript APIs as reasonable.

but received objections

> I had discussion with @MaxGraey and @dcodeIO on this topic and I don't think we reached a consensus. It seems to be something worth further discussion. As @dcodeIO pointed out, because of the static typing nature of assemblyscript, there is going to be some inherent difference between AS and TS. We need to figure out what the plan is regarding supporting typescript syntax, as this is very important going forward.
_Originally posted by @bowenwang1996 in https://github.com/AssemblyScript/meta/pull/4_

so has been removed.

Looks that we should talk about this more closely. From my point of view, there are certain things we should not attempt to support (right now) for various reasons (e.g. tagged pointers because not much is known about WASM64 and potential f64 conflicts) and others that can be supported by implementing them smartly (e.g. limited union types on function parameters implemented similar to generics). Yet, overall, I consider the goal valid because we can't mirror TypeScript exactly, i.e. due to performance implications when diving too deep into interpreter land, but supporting as much of TypeScript as we *reasonably* can without degrading performance seems desirable to meet the "make onboarding easy" goal.

**Comment by torch2424** [comment]
@dcodeIO Thanks for expanding on that. With that, maybe it's just a language thing than? Maybe we can try something like:

`Preserve TypeScript syntax and Javascript APIs, but not at the expense of platform compatibility or performance`.

@bowenwang1996 Is that alright with you? :smile:

**Comment by bowenwang1996** [comment]
I'd like to add that in case where it is necessary, we can introduce syntax that is not supported in typescript. I think @dcodeIO also agrees with this.

**Comment by dcodeIO** [comment]
Yes, adding more features on top of what we have is fine for me *if there is no other way* to make it work with just TypeScript, One such thing is our misuse of decorators as compiler annotations already, or reusing `===` for something different because the original semantics aren't applicable in AS. Future examples could be something like enabling fixed sized arrays, part of an object's memory, as a `foo: SomeObject[50]` type and similar things because it can't be represented with just TS.

**Comment by torch2424** [comment]
@dcodeIO @bowenwang1996 

So I'll admit I'm a bit lost as I probably don't have as much context on the original discussion. :upside_down_face: 

Could one of ya'll propose the goal text than? :smile:

**Comment by dcodeIO** [comment]
Maybe

* Stay backwards-compatible to TypeScript syntax and JavaScript APIs as much as possible.

so we are limited in changing TS/JS but still free to add to it if necessary.

**Comment by torch2424** [comment]
I think that makes sense @dcodeIO . I'll go ahead and add that in 😀

**Comment by MaxGraey** [comment]
@torch2424 btw extra effect of reimplementing JS api / stdlib is fixing correction of historical issues like alphabetical default sorter for any type even for numbers, inconsistencies which avoided by using more strict typing system.

**Comment by dcodeIO** [comment]
Ah, yeah, that's why there's been the "reasonable" wording before. Used that mostly due to the lack of a better word that would better describe "except when what's possible is either really bad (`.sort` implicitly converting to strings) or not applicable (`===` behaving differently per type)".

**Comment by bowenwang1996** [comment]
I think "reasonable" describes it well :)

**Comment by torch2424** [comment]
@MaxGraey @bowenwang1996 @dcodeIO 

Cool, I'll go ahead and do:

`Stay backwards-compatible to TypeScript syntax and JavaScript APIs as much as possible and reasonable.` :joy:

**Comment by torch2424** [comment]
Added to #4
